### BOW Básico

In [1]:
import spacy
import numpy as np
import pandas as pd
from scipy import spatial
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
nlp = spacy.load('en_core_web_sm')

In [3]:
table = pd.read_excel('C:/JupyterLab/github_repos/NLP_project/Dados/df_completo.xlsx')

In [4]:
unprocessed_data = table['Abstract'][0:10].dropna()

#### Pré-processamento

In [5]:
def preprocess_text(series):
    processed_texts = []
    for text in series:
            doc = nlp(text)
            filtered_words = [token.text.lower() for token in doc if not token.is_stop and token.is_alpha]
            processed_texts.append(' '.join(filtered_words))
    return processed_texts


In [6]:
data = preprocess_text(unprocessed_data)
print(data)

['investigated associations dietary intake folate vitamin mthfr t genotype colorectal adenomas dutch case control study data cases histologically confirmed colorectal adenoma n controls history type colorectal polyp n included dietary intake assessed food frequency questionnaire multivariable models included age appropriate dietary folate calcium intake adjusted odds ratio confidence interval ci highest compared lowest sex specific tertile intake ci folate ci vitamin folate risk factor especially vitamin intake low vitamin inversely associated adenomas especially relatively high folate intake association observed mthfr t genotype colorectal adenomas inverse association vitamin intake colorectal adenoma risk pronounced mthfr tt genotype conclude study provide evidence decreased colorectal adenoma risk subjects high dietary intake folate suggests inverse association vitamin colorectal adenomas relevant mthfr tt genotype', 'plasma carotenoid responses determined healthy men women fed cont

#### Plain of Frequency

In [7]:
corpus = list(data)
print(corpus)

['investigated associations dietary intake folate vitamin mthfr t genotype colorectal adenomas dutch case control study data cases histologically confirmed colorectal adenoma n controls history type colorectal polyp n included dietary intake assessed food frequency questionnaire multivariable models included age appropriate dietary folate calcium intake adjusted odds ratio confidence interval ci highest compared lowest sex specific tertile intake ci folate ci vitamin folate risk factor especially vitamin intake low vitamin inversely associated adenomas especially relatively high folate intake association observed mthfr t genotype colorectal adenomas inverse association vitamin intake colorectal adenoma risk pronounced mthfr tt genotype conclude study provide evidence decreased colorectal adenoma risk subjects high dietary intake folate suggests inverse association vitamin colorectal adenomas relevant mthfr tt genotype', 'plasma carotenoid responses determined healthy men women fed cont

In [8]:
vectorizer = CountVectorizer()

In [9]:
bow = vectorizer.fit_transform(corpus)

In [10]:
# View features (tokens).
print(vectorizer.get_feature_names_out())

# View vocabulary dictionary.
vectorizer.vocabulary_

['access' 'accessing' 'according' 'accumulation' 'achieved' 'acid' 'acids'
 'action' 'active' 'activities' 'activity' 'addition' 'additional'
 'address' 'adenocarcinoma' 'adenoma' 'adenomas' 'adipocyte' 'adipocytes'
 'adiponectin' 'adipose' 'adjusted' 'adopting' 'adult' 'adults' 'affect'
 'affects' 'african' 'ag' 'age' 'aged' 'agencies' 'aggregated' 'alcohol'
 'alcoholic' 'alpha' 'alterations' 'altering' 'american' 'analyses'
 'analysis' 'analyze' 'angeles' 'antagonist' 'antigen' 'appropriate'
 'approximate' 'area' 'areas' 'arrangement' 'arthritis' 'aspirin'
 'assessed' 'assessing' 'assessment' 'associated' 'association'
 'associations' 'asthma' 'attainment' 'axis' 'background' 'balance'
 'barrett' 'bas' 'based' 'basel' 'baseline' 'basic' 'basis' 'behavioral'
 'behaviors' 'benign' 'beta' 'better' 'beverages' 'bias' 'binge'
 'biomarkers' 'blood' 'bmi' 'body' 'bone' 'bpe' 'brfss' 'broccoli'
 'calcium' 'caloric' 'calorie' 'calories' 'cancer' 'caratenoid' 'carbon'
 'carcinoma' 'cardiovascu

{'investigated': 396,
 'associations': 57,
 'dietary': 209,
 'intake': 382,
 'folate': 296,
 'vitamin': 773,
 'mthfr': 484,
 'genotype': 312,
 'colorectal': 126,
 'adenomas': 16,
 'dutch': 234,
 'case': 99,
 'control': 155,
 'study': 704,
 'data': 179,
 'cases': 100,
 'histologically': 335,
 'confirmed': 143,
 'adenoma': 15,
 'controls': 158,
 'history': 336,
 'type': 749,
 'polyp': 546,
 'included': 356,
 'assessed': 52,
 'food': 298,
 'frequency': 303,
 'questionnaire': 594,
 'multivariable': 487,
 'models': 471,
 'age': 29,
 'appropriate': 45,
 'calcium': 86,
 'adjusted': 21,
 'odds': 509,
 'ratio': 600,
 'confidence': 142,
 'interval': 387,
 'ci': 115,
 'highest': 333,
 'compared': 132,
 'lowest': 430,
 'sex': 666,
 'specific': 688,
 'tertile': 732,
 'risk': 640,
 'factor': 283,
 'especially': 263,
 'low': 428,
 'inversely': 394,
 'associated': 55,
 'relatively': 621,
 'high': 331,
 'association': 56,
 'observed': 506,
 'inverse': 393,
 'pronounced': 575,
 'tt': 748,
 'conclude': 1

In [11]:
print(bow)

  (0, 396)	1
  (0, 57)	1
  (0, 209)	4
  (0, 382)	8
  (0, 296)	6
  (0, 773)	6
  (0, 484)	4
  (0, 312)	4
  (0, 126)	7
  (0, 16)	4
  (0, 234)	1
  (0, 99)	1
  (0, 155)	1
  (0, 704)	2
  (0, 179)	1
  (0, 100)	1
  (0, 335)	1
  (0, 143)	1
  (0, 15)	3
  (0, 158)	1
  (0, 336)	1
  (0, 749)	1
  (0, 546)	1
  (0, 356)	2
  (0, 52)	1
  :	:
  (9, 285)	1
  (9, 317)	1
  (9, 747)	1
  (9, 421)	1
  (9, 609)	1
  (9, 185)	2
  (9, 523)	1
  (9, 349)	1
  (9, 172)	1
  (9, 664)	6
  (9, 494)	1
  (9, 464)	1
  (9, 259)	1
  (9, 517)	2
  (9, 447)	1
  (9, 399)	2
  (9, 404)	1
  (9, 630)	1
  (9, 133)	1
  (9, 406)	1
  (9, 488)	1
  (9, 467)	1
  (9, 665)	1
  (9, 231)	1
  (9, 53)	1


#### BOW Binário

In [12]:
spacy_tokenizer = lambda doc : [t.text for t in nlp(doc) if not t.is_punct]

In [13]:
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=True)
bow = vectorizer.fit_transform(corpus)

c:\venv\ilumpy-VS\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [14]:
#print(vectorizer.get_feature_names_out())
#vectorizer.vocabulary_

In [15]:
#visualizations
print(bow.toarray())
print()
#print('Indexing and slicing.')
#print(bow[0])
#print()
#print(bow[0:2])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]
 [1 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [0 0 1 ... 1 0 0]]



#### Similaridade por cosseno

In [16]:
bow_array = bow.toarray()

In [17]:
def calculate_cosine_similarity(doc_index1, doc_index2, bow_matrix):
    doc1 = bow_matrix[doc_index1].reshape(1, -1)  # Reshape to 2D array
    doc2 = bow_matrix[doc_index2].reshape(1, -1)  # Reshape to 2D array
    similarity = cosine_similarity(doc1, doc2)
    return similarity[0][0]

def compare_all_documents(bow_matrix):
    num_docs = len(bow_matrix)
    for i in range(num_docs):
        for j in range(i+1, num_docs):
            similarity = calculate_cosine_similarity(i, j, bow_matrix)
            print(f"Doc {i+1} vs Doc {j+1}: {similarity}")


In [18]:
compare_all_documents(bow_array)

Doc 1 vs Doc 2: 0.02561367520589138
Doc 1 vs Doc 3: 0.07452266241066098
Doc 1 vs Doc 4: 0.05363935461248598
Doc 1 vs Doc 5: 0.02185433458832612
Doc 1 vs Doc 6: 0.03396545347417784
Doc 1 vs Doc 7: 0.19645585831566864
Doc 1 vs Doc 8: 0.05396543271993133
Doc 1 vs Doc 9: 0.12037713042133101
Doc 1 vs Doc 10: 0.09014453108339651
Doc 2 vs Doc 3: 0.05595167861550416
Doc 2 vs Doc 4: 0.09205136748895579
Doc 2 vs Doc 5: 0.07500915695015926
Doc 2 vs Doc 6: 0.06557474954819613
Doc 2 vs Doc 7: 0.08428527216546854
Doc 2 vs Doc 8: 0.0
Doc 2 vs Doc 9: 0.020658114829555634
Doc 2 vs Doc 10: 0.03314967720658979
Doc 3 vs Doc 4: 0.10043335633226458
Doc 3 vs Doc 5: 0.06137949055234261
Doc 3 vs Doc 6: 0.620063925730171
Doc 3 vs Doc 7: 0.08429675647647886
Doc 3 vs Doc 8: 0.08420324923030925
Doc 3 vs Doc 9: 0.15026130622691206
Doc 3 vs Doc 10: 0.10448594480358929
Doc 4 vs Doc 5: 0.11781136648171582
Doc 4 vs Doc 6: 0.08392057797258189
Doc 4 vs Doc 7: 0.1654758480803738
Doc 4 vs Doc 8: 0.06060717369568862
Doc 4 v

#### N-Grams

In [19]:
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=True, ngram_range=(1,2))
bigrams = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print('Number of features: {}'.format(len(vectorizer.get_feature_names_out())))
print(vectorizer.vocabulary_)

c:\venv\ilumpy-VS\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


['access' 'access health' 'access insurance' ...
 'zeaxanthin cryptoxanthin' 'zeta' 'zeta carotene']
Number of features: 2308
{'investigated': 1181, 'associations': 181, 'dietary': 653, 'intake': 1143, 'folate': 891, 'vitamin': 2256, 'mthfr': 1435, 't': 2123, 'genotype': 937, 'colorectal': 399, 'adenomas': 43, 'dutch': 724, 'case': 317, 'control': 487, 'study': 2075, 'data': 557, 'cases': 319, 'histologically': 1032, 'confirmed': 453, 'adenoma': 40, 'n': 1446, 'controls': 493, 'history': 1034, 'type': 2197, 'polyp': 1614, 'included': 1075, 'assessed': 165, 'food': 902, 'frequency': 913, 'questionnaire': 1737, 'multivariable': 1442, 'models': 1402, 'age': 99, 'appropriate': 150, 'calcium': 276, 'adjusted': 64, 'odds': 1504, 'ratio': 1752, 'confidence': 450, 'interval': 1163, 'ci': 363, 'highest': 1026, 'compared': 414, 'lowest': 1284, 'sex': 1956, 'specific': 2016, 'tertile': 2148, 'risk': 1863, 'factor': 849, 'especially': 791, 'low': 1278, 'inversely': 1177, 'associated': 173, 'relati

In [20]:
# Setting n_gram range to (2, 2) generates only bigrams.
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=True, ngram_range=(2,2))
bigrams = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(vectorizer.vocabulary_)

['access health' 'access insurance' 'access preventive' ... 'years stroke'
 'zeaxanthin cryptoxanthin' 'zeta carotene']
{'investigated associations': 782, 'associations dietary': 124, 'dietary intake': 443, 'intake folate': 763, 'folate vitamin': 599, 'vitamin mthfr': 1481, 'mthfr t': 948, 't genotype': 1395, 'genotype colorectal': 622, 'colorectal adenomas': 273, 'adenomas dutch': 27, 'dutch case': 488, 'case control': 217, 'control study': 331, 'study data': 1366, 'data cases': 376, 'cases histologically': 218, 'histologically confirmed': 694, 'confirmed colorectal': 309, 'colorectal adenoma': 272, 'adenoma n': 25, 'n controls': 954, 'controls history': 334, 'history type': 695, 'type colorectal': 1443, 'colorectal polyp': 275, 'polyp n': 1063, 'n included': 955, 'included dietary': 717, 'intake assessed': 759, 'assessed food': 114, 'food frequency': 602, 'frequency questionnaire': 608, 'questionnaire multivariable': 1138, 'multivariable models': 952, 'models included': 928, 'include